// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzaGmwEqQZgRWNnhfHrIttGWC1NIB0T2A',
    appId: '1:694854232527:web:ad91edf8230a7d785fcaba',
    messagingSenderId: '694854232527',
    projectId: 'comic-store-57c5f',
    authDomain: 'comic-store-57c5f.firebaseapp.com',
    storageBucket: 'comic-store-57c5f.appspot.com',
    measurementId: 'G-9QSWHZYE6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJtPyaXFloHwIUIQZX_GSsB_WkP8wBSw8',
    appId: '1:694854232527:android:2d3edcd4dadb4d5f5fcaba',
    messagingSenderId: '694854232527',
    projectId: 'comic-store-57c5f',
    storageBucket: 'comic-store-57c5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH9p2dbOfYyiYMcLnPBa5FCNN_eg2ZplI',
    appId: '1:694854232527:ios:09ded7babed883825fcaba',
    messagingSenderId: '694854232527',
    projectId: 'comic-store-57c5f',
    storageBucket: 'comic-store-57c5f.appspot.com',
    androidClientId: '694854232527-b6e605v46qsl0ukj8e9ml5ogv4cr7ni2.apps.googleusercontent.com',
    iosClientId: '694854232527-h5dblfnmhhd0n8n37lql4hurtcfn4fh2.apps.googleusercontent.com',
    iosBundleId: 'com.example.comicStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH9p2dbOfYyiYMcLnPBa5FCNN_eg2ZplI',
    appId: '1:694854232527:ios:09ded7babed883825fcaba',
    messagingSenderId: '694854232527',
    projectId: 'comic-store-57c5f',
    storageBucket: 'comic-store-57c5f.appspot.com',
    androidClientId: '694854232527-b6e605v46qsl0ukj8e9ml5ogv4cr7ni2.apps.googleusercontent.com',
    iosClientId: '694854232527-h5dblfnmhhd0n8n37lql4hurtcfn4fh2.apps.googleusercontent.com',
    iosBundleId: 'com.example.comicStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzaGmwEqQZgRWNnhfHrIttGWC1NIB0T2A',
    appId: '1:694854232527:web:01652a772af1044d5fcaba',
    messagingSenderId: '694854232527',
    projectId: 'comic-store-57c5f',
    authDomain: 'comic-store-57c5f.firebaseapp.com',
    storageBucket: 'comic-store-57c5f.appspot.com',
    measurementId: 'G-X8XB4ZL1K8',
  );
}
